// Compiled shader for custom platforms

//////////////////////////////////////////////////////////////////////////
// 
// NOTE: This is *not* a valid shader file, the contents are provided just
// for information and for debugging purposes only.
// 
//////////////////////////////////////////////////////////////////////////
// Skipping shader variants that would not be included into build of current scene.

Shader "Custom/Textured" {
Properties {
 _MainTex ("Albedo (RGB)", 2D) = "white" { }
}
SubShader { 
 Tags { "RenderType"="Opaque" "LightingMode"="ALWAYS" }
 Pass {
  Tags { "RenderType"="Opaque" "LightingMode"="ALWAYS" }
  Blend SrcAlpha OneMinusSrcAlpha
  //////////////////////////////////
  //                              //
  //      Compiled programs       //
  //                              //
  //////////////////////////////////
//////////////////////////////////////////////////////
Global Keywords: <none>
Local Keywords: <none>
-- Hardware tier variant: Tier 1
-- Vertex shader for "vulkan":
Uses vertex data channel "Vertex"
Uses vertex data channel "Tangent"
Uses vertex data channel "Normal"
Uses vertex data channel "TexCoord0"
Uses vertex data channel "TexCoord1"
Uses vertex data channel "TexCoord2"
Uses vertex data channel "TexCoord3"
Uses vertex data channel "Color"

Set 2D Texture "_MainTex" to set: 0, binding: 1, used in: Fragment  using sampler in set: 0, binding: 0, used in: Fragment 

Constant Buffer "PGlobals638601178" (16 bytes) on set: 1, binding: 0, used in: Fragment  {
  Vector4 _LightColor0 at 0
}
Constant Buffer "VGlobals638601178" (128 bytes) on set: 1, binding: 1, used in: Vertex  {
  Matrix4x4 unity_MatrixVP at 64
  Matrix4x4 unity_ObjectToWorld at 0
}

Shader Disassembly:
Disassembly for Vertex:
// Module Version 10000
// Generated by (magic number): 80006
// Id's are bound by 124

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Vertex 4  "main" 11 72 82 83 87 89 91 92 94 95 97 98 100 101 103 104
                              Name 91  "vs_TEXCOORD0"
                              Name 94  "vs_TEXCOORD1"
                              Name 97  "vs_TEXCOORD2"
                              Name 100  "vs_TEXCOORD3"
                              Decorate 11 Location 0
                              Decorate 16 ArrayStride 16
                              Decorate 17 ArrayStride 16
                              MemberDecorate 18 0 Offset 0
                              MemberDecorate 18 1 Offset 64
                              Decorate 18 Block
                              Decorate 20 DescriptorSet 1
                              Decorate 20 Binding 1
                              MemberDecorate 70 0 BuiltIn Position
                              MemberDecorate 70 1 BuiltIn PointSize
                              MemberDecorate 70 2 BuiltIn ClipDistance
                              Decorate 70 Block
                              Decorate 82 Location 2
                              Decorate 83 Location 1
                              Decorate 87 Location 0
                              Decorate 89 Location 2
                              Decorate 91(vs_TEXCOORD0) Location 1
                              Decorate 92 Location 3
                              Decorate 94(vs_TEXCOORD1) Location 3
                              Decorate 95 Location 4
                              Decorate 97(vs_TEXCOORD2) Location 4
                              Decorate 98 Location 5
                              Decorate 100(vs_TEXCOORD3) Location 5
                              Decorate 101 Location 6
                              Decorate 103 RelaxedPrecision
                              Decorate 103 Location 6
                              Decorate 104 RelaxedPrecision
                              Decorate 104 Location 7
                              Decorate 105 RelaxedPrecision
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypePointer Input 7(fvec4)
              11:     10(ptr) Variable Input
              14:             TypeInt 32 0
              15:     14(int) Constant 4
              16:             TypeArray 7(fvec4) 15
              17:             TypeArray 7(fvec4) 15
              18:             TypeStruct 16 17
              19:             TypePointer Uniform 18(struct)
              20:     19(ptr) Variable Uniform
              21:             TypeInt 32 1
              22:     21(int) Constant 0
              23:     21(int) Constant 1
              24:             TypePointer Uniform 7(fvec4)
              35:     21(int) Constant 2
              44:     21(int) Constant 3
              48:      8(ptr) Variable Private
              68:     14(int) Constant 1
              69:             TypeArray 6(float) 68
              70:             TypeStruct 7(fvec4) 6(float) 69
              71:             TypePointer Output 70(struct)
              72:     71(ptr) Variable Output
              80:             TypePointer Output 7(fvec4)
              82:     80(ptr) Variable Output
              83:     10(ptr) Variable Input
              85:             TypeVector 6(float) 3
              86:             TypePointer Output 85(fvec3)
              87:     86(ptr) Variable Output
              88:             TypePointer Input 85(fvec3)
              89:     88(ptr) Variable Input
91(vs_TEXCOORD0):     80(ptr) Variable Output
              92:     10(ptr) Variable Input
94(vs_TEXCOORD1):     80(ptr) Variable Output
              95:     10(ptr) Variable Input
97(vs_TEXCOORD2):     80(ptr) Variable Output
              98:     10(ptr) Variable Input
100(vs_TEXCOORD3):     80(ptr) Variable Output
             101:     10(ptr) Variable Input
             103:     80(ptr) Variable Output
             104:     10(ptr) Variable Input
             106:             TypePointer Output 6(float)
             112:             TypePointer Function 7(fvec4)
             114:             TypeVector 21(int) 4
             115:             TypePointer Function 114(ivec4)
             117:             TypeBool
             118:             TypeVector 117(bool) 4
             119:             TypePointer Function 118(bvec4)
             121:             TypeVector 14(int) 4
             122:             TypePointer Function 121(ivec4)
               4:           2 Function None 3
               5:             Label
             113:    112(ptr) Variable Function
             116:    115(ptr) Variable Function
             120:    119(ptr) Variable Function
             123:    122(ptr) Variable Function
              12:    7(fvec4) Load 11
              13:    7(fvec4) VectorShuffle 12 12 1 1 1 1
              25:     24(ptr) AccessChain 20 22 23
              26:    7(fvec4) Load 25
              27:    7(fvec4) FMul 13 26
                              Store 9 27
              28:     24(ptr) AccessChain 20 22 22
              29:    7(fvec4) Load 28
              30:    7(fvec4) Load 11
              31:    7(fvec4) VectorShuffle 30 30 0 0 0 0
              32:    7(fvec4) FMul 29 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) FAdd 32 33
                              Store 9 34
              36:     24(ptr) AccessChain 20 22 35
              37:    7(fvec4) Load 36
              38:    7(fvec4) Load 11
              39:    7(fvec4) VectorShuffle 38 38 2 2 2 2
              40:    7(fvec4) FMul 37 39
              41:    7(fvec4) Load 9
              42:    7(fvec4) FAdd 40 41
                              Store 9 42
              43:    7(fvec4) Load 9
              45:     24(ptr) AccessChain 20 22 44
              46:    7(fvec4) Load 45
              47:    7(fvec4) FAdd 43 46
                              Store 9 47
              49:    7(fvec4) Load 9
              50:    7(fvec4) VectorShuffle 49 49 1 1 1 1
              51:     24(ptr) AccessChain 20 23 23
              52:    7(fvec4) Load 51
              53:    7(fvec4) FMul 50 52
                              Store 48 53
              54:     24(ptr) AccessChain 20 23 22
              55:    7(fvec4) Load 54
              56:    7(fvec4) Load 9
              57:    7(fvec4) VectorShuffle 56 56 0 0 0 0
              58:    7(fvec4) FMul 55 57
              59:    7(fvec4) Load 48
              60:    7(fvec4) FAdd 58 59
                              Store 48 60
              61:     24(ptr) AccessChain 20 23 35
              62:    7(fvec4) Load 61
              63:    7(fvec4) Load 9
              64:    7(fvec4) VectorShuffle 63 63 2 2 2 2
              65:    7(fvec4) FMul 62 64
              66:    7(fvec4) Load 48
              67:    7(fvec4) FAdd 65 66
                              Store 48 67
              73:     24(ptr) AccessChain 20 23 44
              74:    7(fvec4) Load 73
              75:    7(fvec4) Load 9
              76:    7(fvec4) VectorShuffle 75 75 3 3 3 3
              77:    7(fvec4) FMul 74 76
              78:    7(fvec4) Load 48
              79:    7(fvec4) FAdd 77 78
              81:     80(ptr) AccessChain 72 22
                              Store 81 79
              84:    7(fvec4) Load 83
                              Store 82 84
              90:   85(fvec3) Load 89
                              Store 87 90
              93:    7(fvec4) Load 92
                              Store 91(vs_TEXCOORD0) 93
              96:    7(fvec4) Load 95
                              Store 94(vs_TEXCOORD1) 96
              99:    7(fvec4) Load 98
                              Store 97(vs_TEXCOORD2) 99
             102:    7(fvec4) Load 101
                              Store 100(vs_TEXCOORD3) 102
             105:    7(fvec4) Load 104
                              Store 103 105
             107:    106(ptr) AccessChain 72 22 68
             108:    6(float) Load 107
             109:    6(float) FNegate 108
             110:    106(ptr) AccessChain 72 22 68
                              Store 110 109
                              Return
                              FunctionEnd

Disassembly for Fragment:
// Module Version 10000
// Generated by (magic number): 80006
// Id's are bound by 83

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint Fragment 4  "main" 12 47 68
                              ExecutionMode 4 OriginUpperLeft
                              Name 47  "vs_TEXCOORD0"
                              Decorate 12 Location 0
                              MemberDecorate 23 0 RelaxedPrecision
                              MemberDecorate 23 0 Offset 0
                              Decorate 23 Block
                              Decorate 25 DescriptorSet 1
                              Decorate 25 Binding 0
                              Decorate 30 RelaxedPrecision
                              Decorate 31 RelaxedPrecision
                              Decorate 35 RelaxedPrecision
                              Decorate 38 RelaxedPrecision
                              Decorate 38 DescriptorSet 0
                              Decorate 38 Binding 1
                              Decorate 39 RelaxedPrecision
                              Decorate 42 RelaxedPrecision
                              Decorate 42 DescriptorSet 0
                              Decorate 42 Binding 0
                              Decorate 43 RelaxedPrecision
                              Decorate 47(vs_TEXCOORD0) Location 1
                              Decorate 54 RelaxedPrecision
                              Decorate 55 RelaxedPrecision
                              Decorate 61 RelaxedPrecision
                              Decorate 64 RelaxedPrecision
                              Decorate 65 RelaxedPrecision
                              Decorate 68 RelaxedPrecision
                              Decorate 68 Location 0
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeFloat 32
               7:             TypeVector 6(float) 4
               8:             TypePointer Private 7(fvec4)
               9:      8(ptr) Variable Private
              10:             TypeVector 6(float) 3
              11:             TypePointer Input 10(fvec3)
              12:     11(ptr) Variable Input
              14:    6(float) Constant 1065353216
              15:   10(fvec3) ConstantComposite 14 14 14
              17:             TypeInt 32 0
              18:     17(int) Constant 0
              19:             TypePointer Private 6(float)
              23:             TypeStruct 7(fvec4)
              24:             TypePointer Uniform 23(struct)
              25:     24(ptr) Variable Uniform
              26:             TypeInt 32 1
              27:     26(int) Constant 0
              28:             TypePointer Uniform 7(fvec4)
              35:      8(ptr) Variable Private
              36:             TypeImage 6(float) 2D sampled format:Unknown
              37:             TypePointer UniformConstant 36
              38:     37(ptr) Variable UniformConstant
              40:             TypeSampler
              41:             TypePointer UniformConstant 40
              42:     41(ptr) Variable UniformConstant
              44:             TypeSampledImage 36
              46:             TypePointer Input 7(fvec4)
47(vs_TEXCOORD0):     46(ptr) Variable Input
              48:             TypeVector 6(float) 2
              59:     17(int) Constant 3
              62:             TypePointer Uniform 6(float)
              67:             TypePointer Output 7(fvec4)
              68:     67(ptr) Variable Output
              71:             TypePointer Function 7(fvec4)
              73:             TypeVector 26(int) 4
              74:             TypePointer Function 73(ivec4)
              76:             TypeBool
              77:             TypeVector 76(bool) 4
              78:             TypePointer Function 77(bvec4)
              80:             TypeVector 17(int) 4
              81:             TypePointer Function 80(ivec4)
               4:           2 Function None 3
               5:             Label
              72:     71(ptr) Variable Function
              75:     74(ptr) Variable Function
              79:     78(ptr) Variable Function
              82:     81(ptr) Variable Function
              13:   10(fvec3) Load 12
              16:    6(float) Dot 13 15
              20:     19(ptr) AccessChain 9 18
                              Store 20 16
              21:    7(fvec4) Load 9
              22:   10(fvec3) VectorShuffle 21 21 0 0 0
              29:     28(ptr) AccessChain 25 27
              30:    7(fvec4) Load 29
              31:   10(fvec3) VectorShuffle 30 30 0 1 2
              32:   10(fvec3) FMul 22 31
              33:    7(fvec4) Load 9
              34:    7(fvec4) VectorShuffle 33 32 4 5 6 3
                              Store 9 34
              39:          36 Load 38
              43:          40 Load 42
              45:          44 SampledImage 39 43
              49:    7(fvec4) Load 47(vs_TEXCOORD0)
              50:   48(fvec2) VectorShuffle 49 49 0 1
              51:    7(fvec4) ImageSampleImplicitLod 45 50
                              Store 35 51
              52:    7(fvec4) Load 9
              53:   10(fvec3) VectorShuffle 52 52 0 1 2
              54:    7(fvec4) Load 35
              55:   10(fvec3) VectorShuffle 54 54 0 1 2
              56:   10(fvec3) FMul 53 55
              57:    7(fvec4) Load 9
              58:    7(fvec4) VectorShuffle 57 56 4 5 6 3
                              Store 9 58
              60:     19(ptr) AccessChain 35 59
              61:    6(float) Load 60
              63:     62(ptr) AccessChain 25 27 59
              64:    6(float) Load 63
              65:    6(float) FMul 61 64
              66:     19(ptr) AccessChain 9 59
                              Store 66 65
              69:    7(fvec4) Load 9
                              Store 68 69
                              Return
                              FunctionEnd

Disassembly for Hull:
Not present.



 }
}
}